# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inspect.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1931, 1312)
        MainWindow.setStyleSheet("QPushButton:hover{\n"
"background-color: #fff;\n"
" color: #000;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
" border: 1px solid #0d6efd;\n"
"                                              padding: 5px 15px;\n"
"                                              outline: 0px;\n"
"}\n"
"QPushButton:pressed {\n"
"    /* 按鈕在被按下時的樣式 */\n"
"background-color: #457dff;\n"
"                                              color: #000;\n"
"                                              font-weight: 600;\n"
"                                              border-radius: 8px;\n"
"                                              border: 1px solid #0d6efd;\n"
"                                              padding: 5px 15px;\n"
"                                              outline: 0px;\n"
"font-size:16px;\n"
"}\n"
"QLabel{\n"
"    border:0px solid;\n"
"}\n"
"QPushButton{\n"
"     background-color: #0d6efd;\n"
"  color: #fff;\n"
"  font-weight: 600;\n"
"  border-radius: 8px;\n"
"  border: 1px solid #10ffff;\n"
"  padding: 5px 15px;\n"
"  outline: 0px;\n"
"  font-size:18px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"        background-color: #55aaff;\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        font-size:18px;\n"
"        padding: 15px;\n"
"          min-height:20px;\n"
"        width:100px;\n"
"border-top-right-radius:15px;\n"
"border-top-left-radius:15px;\n"
"    }\n"
"    QTabBar::tab:hover {\n"
"        background-color: rgb(76, 153, 229);\n"
"    }\n"
"    QTabBar::tab:selected {\n"
"        background-color: #00aa7f;\n"
"    }\n"
"\n"
"/*tabelwidget*/\n"
"QTableWidget{\n"
"color:#111111;\n"
"background:#ffffff;\n"
"border:1px solid #242424;\n"
"alternate-background-color:#525252;/*交错颜色*/\n"
"gridline-color:#242424;\n"
"}\n"
"\n"
"/*选中item*/\n"
"QTableWidget::item:selected{\n"
"color:#DCDCDC;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}\n"
"\n"
"/*\n"
"悬浮item*/\n"
"QTableWidget::item:hover{\n"
"background:#5B5B5B;\n"
"}\n"
"/*表头*/\n"
"QHeaderView::section{\n"
"text-align:center;\n"
"background:#5E5E5E;\n"
"padding:3px;\n"
"margin:0px;\n"
"color:#DCDCDC;\n"
"border:1px solid #242424;\n"
"border-left-width:0;\n"
"}\n"
"\n"
"/*表右侧的滑条*/\n"
"QScrollBar:vertical{\n"
"background:#484848;\n"
"padding:0px;\n"
"border-radius:6px;\n"
"max-width:12px;\n"
"}\n"
"\n"
"/*滑块*/\n"
"QScrollBar::handle:vertical{\n"
"background:#CCCCCC;\n"
"}\n"
"/*\n"
"滑块悬浮，按下*/\n"
"QScrollBar::handle:hover:vertical,QScrollBar::handle:pressed:vertical{\n"
"background:#A7A7A7;\n"
"}\n"
"/*\n"
"滑块已经划过的区域*/\n"
"QScrollBar::sub-page:vertical{\n"
"background:444444;\n"
"}\n"
"\n"
"/*\n"
"滑块还没有划过的区域*/\n"
"QScrollBar::add-page:vertical{\n"
"background:5B5B5B;\n"
"}\n"
"\n"
"/*页面下移的按钮*/\n"
"QScrollBar::add-line:vertical{\n"
"background:none;\n"
"}\n"
"/*页面上移的按钮*/\n"
"QScrollBar::sub-line:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"\n"
"QMessageBox {\n"
"    background-color: #333333;\n"
"}\n"
"\n"
"QMessageBox QLabel {\n"
"    color: #aaa;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(1000, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Main_Page = QtWidgets.QFrame(self.tab)
        self.Main_Page.setMinimumSize(QtCore.QSize(0, 650))
        self.Main_Page.setAutoFillBackground(False)
        self.Main_Page.setStyleSheet("border:0px solid red")
        self.Main_Page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_Page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_Page.setObjectName("Main_Page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Main_Page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Main_frame = QtWidgets.QFrame(self.Main_Page)
        self.Main_frame.setMinimumSize(QtCore.QSize(700, 520))
        self.Main_frame.setMaximumSize(QtCore.QSize(16677, 16777215))
        self.Main_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Main_frame.setStyleSheet("border:1px solid\n"
"")
        self.Main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_frame.setObjectName("Main_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.Main_frame)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.Main_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(450, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout.addWidget(self.frame_3, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.Main_frame)
        self.frame_4.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(1666666, 200))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Main_Frame_reset = QtWidgets.QPushButton(self.frame_4)
        self.Main_Frame_reset.setMinimumSize(QtCore.QSize(0, 80))
        self.Main_Frame_reset.setMaximumSize(QtCore.QSize(120, 80))
        self.Main_Frame_reset.setObjectName("Main_Frame_reset")
        self.horizontalLayout_4.addWidget(self.Main_Frame_reset)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.gridLayout.addWidget(self.frame_4, 2, 0, 1, 1)
        self.MenuBar = QtWidgets.QFrame(self.Main_frame)
        self.MenuBar.setMinimumSize(QtCore.QSize(400, 100))
        self.MenuBar.setMaximumSize(QtCore.QSize(16777215, 80))
        self.MenuBar.setStyleSheet("border:1px  solid black\n"
"")
        self.MenuBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuBar.setObjectName("MenuBar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MenuBar)
        self.gridLayout_2.setContentsMargins(11, 11, -1, -1)
        self.gridLayout_2.setSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.MenuBar)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Main_Cam_IP_label = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Main_Cam_IP_label.setFont(font)
        self.Main_Cam_IP_label.setStyleSheet("border:0px solid;")
        self.Main_Cam_IP_label.setObjectName("Main_Cam_IP_label")
        self.horizontalLayout_5.addWidget(self.Main_Cam_IP_label)
        self.Main_Cam_IP = QtWidgets.QLineEdit(self.frame_10)
        self.Main_Cam_IP.setMinimumSize(QtCore.QSize(300, 0))
        self.Main_Cam_IP.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Main_Cam_IP.setFont(font)
        self.Main_Cam_IP.setStyleSheet("margin:0px;\n"
"top:-20px")
        self.Main_Cam_IP.setText("")
        self.Main_Cam_IP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Main_Cam_IP.setObjectName("Main_Cam_IP")
        self.horizontalLayout_5.addWidget(self.Main_Cam_IP)
        self.Main_Connected = QtWidgets.QPushButton(self.frame_10)
        self.Main_Connected.setObjectName("Main_Connected")
        self.horizontalLayout_5.addWidget(self.Main_Connected)
        self.gridLayout_2.addWidget(self.frame_10, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Main_finger_detect = QtWidgets.QPushButton(self.MenuBar)
        self.Main_finger_detect.setObjectName("Main_finger_detect")
        self.gridLayout_2.addWidget(self.Main_finger_detect, 0, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.MenuBar, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.Main_frame)
        self.label.setMinimumSize(QtCore.QSize(1200, 720))
        self.label.setMaximumSize(QtCore.QSize(1200, 720))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.Main_frame)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_11.setStyleSheet("border:0px solid;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:0px solid")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.Main_Prod_ID = QtWidgets.QLineEdit(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Main_Prod_ID.setFont(font)
        self.Main_Prod_ID.setStyleSheet("border:1px solid;")
        self.Main_Prod_ID.setObjectName("Main_Prod_ID")
        self.horizontalLayout_7.addWidget(self.Main_Prod_ID)
        self.gridLayout_3.addWidget(self.frame_12, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.Leave = QtWidgets.QPushButton(self.frame_11)
        self.Leave.setMinimumSize(QtCore.QSize(80, 40))
        self.Leave.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Leave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Leave.setStyleSheet("QPushButton:hover,\n"
"QPushButton:focus {\n"
"  background-color: #ea0101;\n"
"  border: 3px solid #9ac3fe;\n"
"}")
        self.Leave.setObjectName("Leave")
        self.gridLayout_3.addWidget(self.Leave, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.Main_Prod_SN = QtWidgets.QLineEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Main_Prod_SN.setFont(font)
        self.Main_Prod_SN.setStyleSheet("border:1px solid;")
        self.Main_Prod_SN.setObjectName("Main_Prod_SN")
        self.horizontalLayout_3.addWidget(self.Main_Prod_SN)
        self.gridLayout_3.addWidget(self.frame_13, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_11, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.Main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(500, 100))
        self.frame_2.setMaximumSize(QtCore.QSize(800, 800))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.frame_2.setFont(font)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_14 = QtWidgets.QFrame(self.frame_2)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Main_Crop1 = QtWidgets.QLabel(self.frame_14)
        self.Main_Crop1.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop1.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Main_Crop1.setFont(font)
        self.Main_Crop1.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop1.setObjectName("Main_Crop1")
        self.horizontalLayout_6.addWidget(self.Main_Crop1)
        self.Main_Crop6 = QtWidgets.QLabel(self.frame_14)
        self.Main_Crop6.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop6.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.Main_Crop6.setFont(font)
        self.Main_Crop6.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop6.setObjectName("Main_Crop6")
        self.horizontalLayout_6.addWidget(self.Main_Crop6)
        self.verticalLayout.addWidget(self.frame_14, 0, QtCore.Qt.AlignHCenter)
        self.frame_15 = QtWidgets.QFrame(self.frame_2)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Main_Crop2 = QtWidgets.QLabel(self.frame_15)
        self.Main_Crop2.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop2.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.Main_Crop2.setFont(font)
        self.Main_Crop2.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop2.setObjectName("Main_Crop2")
        self.horizontalLayout_8.addWidget(self.Main_Crop2)
        self.Main_Crop7 = QtWidgets.QLabel(self.frame_15)
        self.Main_Crop7.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop7.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.Main_Crop7.setFont(font)
        self.Main_Crop7.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop7.setObjectName("Main_Crop7")
        self.horizontalLayout_8.addWidget(self.Main_Crop7)
        self.verticalLayout.addWidget(self.frame_15, 0, QtCore.Qt.AlignHCenter)
        self.frame_16 = QtWidgets.QFrame(self.frame_2)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Main_Crop3 = QtWidgets.QLabel(self.frame_16)
        self.Main_Crop3.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop3.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.Main_Crop3.setFont(font)
        self.Main_Crop3.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop3.setObjectName("Main_Crop3")
        self.horizontalLayout_9.addWidget(self.Main_Crop3)
        self.Main_Crop8 = QtWidgets.QLabel(self.frame_16)
        self.Main_Crop8.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop8.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.Main_Crop8.setFont(font)
        self.Main_Crop8.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop8.setObjectName("Main_Crop8")
        self.horizontalLayout_9.addWidget(self.Main_Crop8)
        self.verticalLayout.addWidget(self.frame_16, 0, QtCore.Qt.AlignHCenter)
        self.frame_17 = QtWidgets.QFrame(self.frame_2)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Main_Crop4 = QtWidgets.QLabel(self.frame_17)
        self.Main_Crop4.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop4.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.Main_Crop4.setFont(font)
        self.Main_Crop4.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop4.setObjectName("Main_Crop4")
        self.horizontalLayout_10.addWidget(self.Main_Crop4)
        self.Main_Crop9 = QtWidgets.QLabel(self.frame_17)
        self.Main_Crop9.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop9.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.Main_Crop9.setFont(font)
        self.Main_Crop9.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop9.setObjectName("Main_Crop9")
        self.horizontalLayout_10.addWidget(self.Main_Crop9)
        self.verticalLayout.addWidget(self.frame_17, 0, QtCore.Qt.AlignHCenter)
        self.frame_18 = QtWidgets.QFrame(self.frame_2)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Main_Crop5 = QtWidgets.QLabel(self.frame_18)
        self.Main_Crop5.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop5.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.Main_Crop5.setFont(font)
        self.Main_Crop5.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop5.setObjectName("Main_Crop5")
        self.horizontalLayout_11.addWidget(self.Main_Crop5, 0, QtCore.Qt.AlignHCenter)
        self.Main_Crop10 = QtWidgets.QLabel(self.frame_18)
        self.Main_Crop10.setMinimumSize(QtCore.QSize(200, 100))
        self.Main_Crop10.setMaximumSize(QtCore.QSize(192, 144))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.Main_Crop10.setFont(font)
        self.Main_Crop10.setAlignment(QtCore.Qt.AlignCenter)
        self.Main_Crop10.setObjectName("Main_Crop10")
        self.horizontalLayout_11.addWidget(self.Main_Crop10, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_18, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.frame_2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.Main_frame)
        self.verticalLayout_6.addWidget(self.Main_Page)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Setting_Table_Area = QtWidgets.QStackedWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        self.Setting_Table_Area.setFont(font)
        self.Setting_Table_Area.setObjectName("Setting_Table_Area")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tableWidget = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget.setMinimumSize(QtCore.QSize(700, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_13.addWidget(self.tableWidget)
        self.Setting_Table_Area.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget2 = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget2.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget2.setFont(font)
        self.tableWidget2.setAutoFillBackground(False)
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(2)
        self.tableWidget2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(1, item)
        self.tableWidget2.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.tableWidget2)
        self.frame_19 = QtWidgets.QFrame(self.page_4)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Setting_Save = QtWidgets.QPushButton(self.frame_19)
        self.Setting_Save.setMinimumSize(QtCore.QSize(200, 40))
        self.Setting_Save.setObjectName("Setting_Save")
        self.horizontalLayout_12.addWidget(self.Setting_Save, 0, QtCore.Qt.AlignHCenter)
        self.Setting_Back_Save = QtWidgets.QPushButton(self.frame_19)
        self.Setting_Back_Save.setMinimumSize(QtCore.QSize(200, 40))
        self.Setting_Back_Save.setObjectName("Setting_Back_Save")
        self.horizontalLayout_12.addWidget(self.Setting_Back_Save, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.frame_19)
        self.Setting_Table_Area.addWidget(self.page_4)
        self.horizontalLayout.addWidget(self.Setting_Table_Area)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(800, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 800))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.page)
        self.frame_7.setMinimumSize(QtCore.QSize(800, 0))
        self.frame_7.setStyleSheet("border:1px solid")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Setting_Build_Data = QtWidgets.QPushButton(self.frame_8)
        self.Setting_Build_Data.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Setting_Build_Data.setFont(font)
        self.Setting_Build_Data.setStyleSheet("")
        self.Setting_Build_Data.setObjectName("Setting_Build_Data")
        self.verticalLayout_11.addWidget(self.Setting_Build_Data)
        self.verticalLayout_10.addWidget(self.frame_8, 0, QtCore.Qt.AlignTop)
        self.Setting_Setup_img = QtWidgets.QLabel(self.frame_7)
        self.Setting_Setup_img.setMinimumSize(QtCore.QSize(800, 600))
        self.Setting_Setup_img.setMaximumSize(QtCore.QSize(1280, 800))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.Setting_Setup_img.setFont(font)
        self.Setting_Setup_img.setAlignment(QtCore.Qt.AlignCenter)
        self.Setting_Setup_img.setObjectName("Setting_Setup_img")
        self.verticalLayout_10.addWidget(self.Setting_Setup_img)
        self.verticalLayout_9.addWidget(self.frame_7, 0, QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_9 = QtWidgets.QFrame(self.page_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_9)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_6.setMaximumSize(QtCore.QSize(500, 550))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout.setContentsMargins(-1, 0, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.Setting_prod_name = QtWidgets.QLineEdit(self.frame_6)
        self.Setting_prod_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Setting_prod_name.setFont(font)
        self.Setting_prod_name.setText("")
        self.Setting_prod_name.setAlignment(QtCore.Qt.AlignCenter)
        self.Setting_prod_name.setObjectName("Setting_prod_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Setting_prod_name)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.Setting_prod_id = QtWidgets.QLineEdit(self.frame_6)
        self.Setting_prod_id.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Setting_prod_id.setFont(font)
        self.Setting_prod_id.setText("")
        self.Setting_prod_id.setAlignment(QtCore.Qt.AlignCenter)
        self.Setting_prod_id.setObjectName("Setting_prod_id")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Setting_prod_id)
        self.Setting_archiving = QtWidgets.QPushButton(self.frame_6)
        self.Setting_archiving.setMinimumSize(QtCore.QSize(0, 40))
        self.Setting_archiving.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Setting_archiving.setObjectName("Setting_archiving")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Setting_archiving)
        self.Setting_prod_area = QtWidgets.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Setting_prod_area.setFont(font)
        self.Setting_prod_area.setText("")
        self.Setting_prod_area.setAlignment(QtCore.Qt.AlignCenter)
        self.Setting_prod_area.setObjectName("Setting_prod_area")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Setting_prod_area)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setIndent(0)
        self.label_7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.Setting_BackSetup = QtWidgets.QPushButton(self.frame_9)
        self.Setting_BackSetup.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Setting_BackSetup.setObjectName("Setting_BackSetup")
        self.horizontalLayout_2.addWidget(self.Setting_BackSetup, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_12.addWidget(self.frame_9, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_8.addWidget(self.stackedWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_7.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1931, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Setting_Table_Area.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.Main_Frame_reset.setText(_translate("MainWindow", "RESET"))
        self.Main_Cam_IP_label.setText(_translate("MainWindow", "IP CAM : "))
        self.Main_Connected.setText(_translate("MainWindow", "連線"))
        self.Main_finger_detect.setText(_translate("MainWindow", "偵測手勢"))
        self.label.setText(_translate("MainWindow", "waitting frame..."))
        self.label_3.setText(_translate("MainWindow", "產品ID : "))
        self.Leave.setText(_translate("MainWindow", "X"))
        self.label_6.setText(_translate("MainWindow", "包裝SN : "))
        self.Main_Crop1.setText(_translate("MainWindow", "1"))
        self.Main_Crop6.setText(_translate("MainWindow", "6"))
        self.Main_Crop2.setText(_translate("MainWindow", "2"))
        self.Main_Crop7.setText(_translate("MainWindow", "7"))
        self.Main_Crop3.setText(_translate("MainWindow", "3"))
        self.Main_Crop8.setText(_translate("MainWindow", "8"))
        self.Main_Crop4.setText(_translate("MainWindow", "4"))
        self.Main_Crop9.setText(_translate("MainWindow", "9"))
        self.Main_Crop5.setText(_translate("MainWindow", "5"))
        self.Main_Crop10.setText(_translate("MainWindow", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "即時頁面"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product_ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ZoneCount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Position"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Setup_time"))
        item = self.tableWidget2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Order"))
        item = self.tableWidget2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Position"))
        self.Setting_Save.setText(_translate("MainWindow", "保存"))
        self.Setting_Back_Save.setText(_translate("MainWindow", "退出"))
        self.Setting_Build_Data.setText(_translate("MainWindow", "新增資料"))
        self.Setting_Setup_img.setText(_translate("MainWindow", "欲設定偵測區域\n"
"請點擊產品列表指定型號"))
        self.label_4.setText(_translate("MainWindow", "品名"))
        self.label_5.setText(_translate("MainWindow", "編號"))
        self.Setting_archiving.setText(_translate("MainWindow", "送出"))
        self.label_7.setText(_translate("MainWindow", "偵測框數量"))
        self.Setting_BackSetup.setText(_translate("MainWindow", "返回"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "設定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
